"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, GraduationCap, Layers3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const YEARS = ["1st Year", "2nd Year", "3rd Year", "4th Year"];
export function ClassOnboardingForm({ defaultYear }: { defaultYear?: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form.entries()); try { const response = await fetch("/api/classes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Could not create the classroom."); router.push(`/admin/classes/${data.id}/overview`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create the classroom."); setPending(false); } }
  return <form onSubmit={(event) => void submit(event)} className="mx-auto max-w-4xl space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-300">Academic setup</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-white">Create a classroom</h1><p className="mt-2 text-sm text-slate-400">Start with the year and group. Your staff can then add students, syllabus and scheduled tests from the classroom workspace.</p></div>
    <Card className="space-y-5"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-500/15 text-violet-300"><GraduationCap className="h-5 w-5" /></span><div><h2 className="font-semibold text-white">1. Academic placement</h2><p className="mt-1 text-sm text-slate-500">This controls where the classroom appears in the directory.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Academic year"><select name="academicYear" defaultValue={YEARS.includes(defaultYear ?? "") ? defaultYear : "1st Year"} className="input-select">{YEARS.map((year) => <option key={year}>{year}</option>)}</select></Field><Field label="Program / course" optional><Input name="program" placeholder="e.g. B.Tech, Intermediate MPC" maxLength={100} /></Field><Field label="Group / branch"><Input name="groupName" placeholder="e.g. CSE, MPC, BiPC" required maxLength={80} /></Field><Field label="Section" optional><Input name="section" placeholder="e.g. A, B, Morning batch" maxLength={40} /></Field></div></Card>
    <Card className="space-y-5"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/15 text-blue-300"><Layers3 className="h-5 w-5" /></span><div><h2 className="font-semibold text-white">2. Classroom identity</h2><p className="mt-1 text-sm text-slate-500">Use a name your team will recognize immediately.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Classroom name"><Input name="name" placeholder="e.g. 1st CSE · Section A" required minLength={2} /></Field><Field label="Primary subject"><Input name="subject" placeholder="e.g. Engineering Mathematics" required minLength={2} /></Field><Field label="Notes for staff" optional><textarea name="description" rows={4} maxLength={1000} placeholder="Learning goals, faculty note or batch details…" className="input-select sm:col-span-2" /></Field></div></Card>
    {error ? <p role="alert" className="rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p> : null}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => router.back()} disabled={pending}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? "Creating…" : <>Create classroom <ArrowRight className="h-4 w-4" /></>}</Button></div></form>;
}
function Field({ label, optional, children }: { label: string; optional?: boolean; children: React.ReactNode }) { return <label className="space-y-1.5 text-sm text-slate-300"><span>{label} {optional ? <span className="text-xs text-slate-600">optional</span> : <span className="text-rose-300">*</span>}</span>{children}</label>; }
